Update CodeQualityCheck.yml

diff --git a/.github/workflows/CodeQualityCheck.yml b/.github/workflows/CodeQualityCheck.yml
--- a/.github/workflows/CodeQualityCheck.yml
+++ b/.github/workflows/CodeQualityCheck.yml
@@ -48,7 +48,6 @@ jobs:
             git commit -m "Auto-format code for PR" || echo "No formatting changes to commit."
           else
             echo "All files are properly formatted."
-          exit 1
 
   dart_fix:
     name: Dart Fix
@@ -167,3 +166,56 @@ jobs:
           echo "Running unit tests..."
           flutter test
         continue-on-error: true  # Fail the job if tests do not pass
+
+  check_todo:
+    name: Check For TODO Comments
+    runs-on: ubuntu-latest
+    needs: setup
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Fetch base branch
+        run: git fetch origin ${{ github.base_ref }}
+
+      - name: Setup Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          flutter-version: '3.19.6'
+
+      - name: Install dependencies
+        run: flutter pub get
+
+      - name: Check for TODO Comments in Changed Dart Files
+        run: |
+          echo "Checking for TODO comments in changed Dart files..."
+
+          # Fetch both the base and head branches
+          git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}
+
+          # Get a list of changed Dart files in the PR
+          CHANGED_DART_FILES=$(git diff --name-only --diff-filter=AMR origin/${{ github.base_ref }}...origin/${{ github.head_ref }} -- | grep -E '\.dart$')
+
+          if [ -z "$CHANGED_DART_FILES" ]; then
+            echo "No changed Dart files to check for TODOs."
+            exit 0
+          fi
+
+          # Initialize a variable to track files with TODOs
+          TODO_FILES=""
+
+          # Loop through changed Dart files to find TODO comments
+          for file in $CHANGED_DART_FILES; do
+            if grep -q "TODO" "$file"; then
+              TODO_FILES="$TODO_FILES\n$file"
+            fi
+          done
+
+          # Report files with TODO comments or indicate that none were found
+          if [ -n "$TODO_FILES" ]; then
+            echo "TODO comments found in the following Dart files:"
+            echo -e "$TODO_FILES"
+            exit 1  # Exit with failure if TODO comments are found
+          else
+            echo "No TODO comments found in changed Dart files."
+          fi
