Update update-pubspec.yml

diff --git a/.github/workflows/update-pubspec.yml b/.github/workflows/update-pubspec.yml
--- a/.github/workflows/update-pubspec.yml
+++ b/.github/workflows/update-pubspec.yml
@@ -16,6 +16,11 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
 
+    - name: Set up SSH
+      uses: webfactory/ssh-agent@v0.5.3
+      with:
+        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+
     - name: Set up Flutter
       uses: subosito/flutter-action@v2
       with:
@@ -41,7 +46,8 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Install dependencies
-      run: flutter pub get
+      run: |
+        flutter pub get || (echo "pub get failed, running pub upgrade..." && flutter pub upgrade)
 
     - name: Analyze code
       id: analyze
