Update update-pubspec.yml

diff --git a/.github/workflows/update-pubspec.yml b/.github/workflows/update-pubspec.yml
--- a/.github/workflows/update-pubspec.yml
+++ b/.github/workflows/update-pubspec.yml
@@ -49,31 +49,31 @@ jobs:
     #   run: |
     #     flutter pub get || (echo "pub get failed, running pub upgrade..." && flutter pub upgrade)
 
-    - name: Analyze code
-      id: analyze
-      run: |
-        set +e  # Allow the script to continue even if there are errors
-        analyze_output=$(flutter analyze)
-        echo "$analyze_output"
+    # - name: Analyze code
+    #   id: analyze
+    #   run: |
+    #     set +e  # Allow the script to continue even if there are errors
+    #     analyze_output=$(flutter analyze)
+    #     echo "$analyze_output"
 
-        # Count errors and warnings
-        error_count=$(echo "$analyze_output" | grep -o '• [0-9]\+ error' | grep -o '[0-9]\+')
-        warning_count=$(echo "$analyze_output" | grep -o '• [0-9]\+ warning' | grep -o '[0-9]\+')
+    #     # Count errors and warnings
+    #     error_count=$(echo "$analyze_output" | grep -o '• [0-9]\+ error' | grep -o '[0-9]\+')
+    #     warning_count=$(echo "$analyze_output" | grep -o '• [0-9]\+ warning' | grep -o '[0-9]\+')
 
-        echo "Error count: $error_count"
-        echo "Warning count: $warning_count"
+    #     echo "Error count: $error_count"
+    #     echo "Warning count: $warning_count"
 
-        # Set the outputs for the next step
-        echo "::set-output name=error_count::$error_count"
-        echo "::set-output name=warning_count::$warning_count"
+    #     # Set the outputs for the next step
+    #     echo "::set-output name=error_count::$error_count"
+    #     echo "::set-output name=warning_count::$warning_count"
 
-    - name: Check for errors
-      if: steps.analyze.outputs.error_count != '0'
-      run: |
-        echo "Errors detected: ${{ steps.analyze.outputs.error_count }}. Failing the build."
-        exit 1
+    # - name: Check for errors
+    #   if: steps.analyze.outputs.error_count != '0'
+    #   run: |
+    #     echo "Errors detected: ${{ steps.analyze.outputs.error_count }}. Failing the build."
+    #     exit 1
 
-    - name: Report warnings
-      if: steps.analyze.outputs.error_count == '0'
-      run: |
-        echo "No errors found. Warnings: ${{ steps.analyze.outputs.warning_count }}"
+    # - name: Report warnings
+    #   if: steps.analyze.outputs.error_count == '0'
+    #   run: |
+    #     echo "No errors found. Warnings: ${{ steps.analyze.outputs.warning_count }}"
